### ISSUE TITLE
pip install miss cython

### ISSUE THREAD

**Issue by mmmaat** [bootphon/ABXpy#11]
@louisabraham thanks for your PR. I just tried it on a fresh conda environment. It works but need `cython` installed. So the installation section of the README should be, no?

```
pip install cython
pip install git+https://github.com/bootphon/ABXpy
```

**Comment by louisabraham** [comment]
One would also need unittest2 to actually use h5py.

See `.travis.yml`:

      # TODO: remove cython, it should be handled https://github.com/pypa/setuptools/issues/1317
      # TODO: remove unittest2, the error got fixed this morning https://github.com/h5py/h5py/commit/a54de719751c58029f22ed0d00c5d8c51a873e8a
      - conda create --yes -q -n test-environment python=$TRAVIS_PYTHON_VERSION unittest2 cython

The h5py bug has been fixed today by a commit. Maybe the cython problem is a feature?

For the moment, it is indeed safer to install cython.
