### ISSUE TITLE
Undefined behavior

### ISSUE THREAD

**Issue by louisabraham** [bootphon/ABXpy#14]
Some outputs are determined by an iteration order on sets / dicts.
They are guaranteed to be consistent for multiple executions, but not across versions.

I think the csv test in test_frozen_analyze is the only one concerned.

Do you prefer:
- to correct the undefined behavior (more complicated and since the tests will be changed there is a risk of breaking something but it is ultimately cleaner)? 
- to make separate tests for different Python versions (simplest to implement)?

**Comment by mmmaat** [comment]
Fixed as of [ABXpy-0.4.2](https://github.com/bootphon/ABXpy/commit/3d552d777dae322603c797bdc803775482bac960).
