### ISSUE TITLE
table package

### ISSUE THREAD

**Issue by jubenjum** [bootphon/ABXpy#2]
Hi

I found that the package tables loaded in: 

https://github.com/bootphon/ABXpy/blob/fa7bf72a6d0ed455e676eb3912b2e19a3740e447/ABXpy/task.py#L72

is not in the  requirements.txt. Which package is it?

Thanks for the info.

Juan

**Comment by mmmaat** [comment]
Hi Juan, if I remember correctly just have a `pip install pytables`...
