### ISSUE TITLE
Huge git repo size

### ISSUE THREAD

**Issue by louisabraham** [bootphon/ABXpy#8]
There is an enormous (33Mb) pack file that is always cloned, even when using `git clone --depth 1`. 

The biggest files in the pack file seem to be:
- MFCC.tar.gz
- resources/english.item
- HTKposteriors.tar.gz
- resources/xitsonga.item
- ABXpy/test/frozen_files/data.abx
- resources/sample.item
…

Apart from ABXpy/test/frozen_files/data.abx, they all seem to have been deleted. Would it be possible to clean the pack file?

**Comment by mmmaat** [comment]
Hi Louis,

Just having a `git clone --depth 1 --branch master` is fine if you want a minimal repo size (1.5MB). You are welcome to clean the pack file if you want to ;)

**Comment by louisabraham** [comment]
My bad, didn't see the other branches.
